name: Generate Release Notes

on:
  release:
    types: [published]

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate release notes
        run: |
          echo "## Release Notes" > release-notes.md
          cat pr-titles.txt >> release-notes.md

      - name: Commit release notes
        run: |
          git config --global user.name 'ilia-markovski-jdm'
          git config --global user.email 'i.markovski@jdm.de'
          git add release-notes.md
          git commit -m "Add release notes"
          git push
